
language: cpp
compiler:
  - gcc
  
install:
- wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1204/x86_64/cuda-repo-ubuntu1204_7.0-28_amd64.deb
- sudo dpkg -i cuda-repo-ubuntu1204_7.0-28_amd64.deb
- sudo apt-get update -qq
- sudo apt-get install cuda
script:
- ls
- make
