#
# Use ubuntu trusty (14.04) with sudo privileges.
dist: trusty
sudo: required
language:
  - generic
cache:
  - apt

language: cpp
compiler:
  - gcc
  
before_script:
 - sudo apt-get update -qq
 - sudo apt-get install -qq build-essential
 - sudo apt-get install -qq gcc-4.4
 - sudo apt-get install -qq nvidia-common
 - sudo apt-get install -qq nvidia-current
 - sudo apt-get install -qq nvidia-cuda-toolkit nvidia-cuda-dev

script: make
