
language: cpp
compiler:
  - gcc
  
install:
- wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1204/x86_64/cuda-repo-ubuntu1204_7.0-28_amd64.deb
- sudo dpkg -i cuda-repo-ubuntu1204_7.0-28_amd64.deb
- sudo apt-get update -qq
- sudo apt-get install cuda
script:
- export PATH=/usr/local/cuda-7.0/bin/:${PATH}
- nvcc -O3 -Xcompiler="-fopenmp" -arch=compute_20 -code=compute_20 -I. nlm.cc cuda_nlm.cu cuda_nlm_smem.cu timer.cc -o cunlm
